[build]
  command = "vite build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Configuration des formulaires
[build.processing.html]
  pretty_urls = true

# Configuration des notifications par email
[[forms]]
  name = "contact"
  success_url = "/success"